"""empty message

Revision ID: 7ca9b633d8f5
Revises: edcec73ffb2b
Create Date: 2020-05-05 15:50:40.745843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca9b633d8f5'
down_revision = 'edcec73ffb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('html_stats',
    sa.Column('loc', sa.String(length=2083), nullable=False),
    sa.Column('domain', sa.String(length=2083), nullable=False),
    sa.Column('path', sa.String(length=2083), nullable=False),
    sa.Column('create_at', sa.DATETIME(), nullable=False),
    sa.Column('update_at', sa.DATETIME(), nullable=False),
    sa.Column('word_count', sa.INTEGER(), nullable=False),
    sa.Column('number_of_punctuation_marks', sa.INTEGER(), nullable=False),
    sa.Column('number_of_h1', sa.INTEGER(), nullable=False),
    sa.Column('number_of_h2', sa.INTEGER(), nullable=False),
    sa.Column('number_of_h3', sa.INTEGER(), nullable=False),
    sa.Column('number_of_h4', sa.INTEGER(), nullable=False),
    sa.Column('number_of_h5', sa.INTEGER(), nullable=False),
    sa.Column('number_of_h6', sa.INTEGER(), nullable=False),
    sa.Column('number_of_table', sa.INTEGER(), nullable=False),
    sa.Column('number_of_li', sa.INTEGER(), nullable=False),
    sa.Column('number_of_dl', sa.INTEGER(), nullable=False),
    sa.Column('number_of_image', sa.INTEGER(), nullable=False),
    sa.Column('number_of_a', sa.INTEGER(), nullable=False),
    sa.Column('number_of_iframe', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('loc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('html_stats')
    # ### end Alembic commands ###
