"""empty message

Revision ID: edcec73ffb2b
Revises: 
Create Date: 2020-05-05 14:43:12.191525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edcec73ffb2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_sitemap',
    sa.Column('loc', sa.String(length=2083), nullable=False),
    sa.Column('domain', sa.String(length=2083), nullable=False),
    sa.Column('path', sa.String(length=2083), nullable=False),
    sa.Column('lastmod', sa.DATETIME(), nullable=True),
    sa.Column('change_freq', sa.String(length=10), nullable=True),
    sa.Column('priority', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.Enum('before_html_stats', 'failed_html_stats', 'task_done', name='sitemaptaskstatus'), nullable=True),
    sa.PrimaryKeyConstraint('loc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_sitemap')
    # ### end Alembic commands ###
